name = "aes/credit-policy"
version = "0.1.0"
license = "Apache-2.0"
description = "AES CREDIT token minting policy"

[repository]
user = "AEL"
project = "aes-credit"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v2.2.0"
source = "github"
